name: Build Artifacts

on:
  push:
    branches: [ main, master ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application for production
      run: npm run build -- --configuration=production
      
    - name: Create artifact archive
      run: |
        cd dist/angular-app
        tar -czf ../../familiada-app.tar.gz *
        cd ../..
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: familiada-app-${{ github.sha }}
        path: |
          dist/angular-app/
          familiada-app.tar.gz
        retention-days: 30
        
    - name: Upload release assets (on release)
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./familiada-app.tar.gz
        asset_name: familiada-app-${{ github.event.release.tag_name }}.tar.gz
        asset_content_type: application/gzip